#!/bin/sh

# ensure that these programs exist
program="xclip"
if ! command -v "$program" >/dev/null 2>&1; then
  echo "Error: program $program is missing!"
  exit 1
fi

# clipboard is now primary
xclip -o -selection clipboard | xclip -i
