#!/bin/sh

# strict mode
set -eu

# get windows processes
procs=$(wmctrl -p -l -x)
if [ -z "$procs" ]; then
  echo "Error: no processes found"
  exit 1
fi

# terminate selected window process
num_procs=$(echo "$procs" | wc -l)
pid=$(echo "$procs" | cut -d ' ' -f4- | dmenu -l "$num_procs" | cut -d ' ' -f1)
if [ -n "$pid" ]; then
  # check if pid is numeric
  if [ "$pid" -eq "$pid" ] 2>/dev/null; then
    kill "$pid"
    # send SIGKILL if pid still exists
    if ps -p "$pid" >/dev/null 2>&1; then
      kill -KILL "$pid"
    fi
  else
    echo "Error: pid is non-numeric"
    exit 1
  fi
fi
