#!/bin/sh

# strict mode
set -eu

# reset keymap options
setxkbmap -option

# get current keyboard layout
curlayout=$(setxkbmap -query | awk '/^layout:/ { print $2 }')

# toggle between english and russian keyboard
if [ "$curlayout" = "us" ]; then
  layout="ru"
else
  layout="us"
fi

# set the keyboard
setxkbmap -layout $layout \
          -option caps:super \
          -option shift:both_capslock_cancel \
          -option ctrl:swap_lalt_lctl \
          -option ctrl:ralt_rctrl \
          -option ctrl:rctrl_ralt \
          -option compose:paus
