#!/bin/sh
# Distributed under the terms of the GNU General Public License v3

# strict mode
set -eu

# settings
progname="volume" # program name
volmaster="90"    # default master volume
voladjust="5"     # value to increase/decrease volume

# help usage info
help() {
  echo "Usage: $progname up|down|toggle|restore"
}

# shows the message and exits the program
panic() {
  echo "$@" 1>&2
  exit 1
}

# get the app sinks from the active window
getappsinks() {
  # TODO xdotool getactivewindow getwindowclassname
  class=$(xprop -id "$(xdotool getactivewindow)" | awk -F '"' '/^WM_CLASS\(/ { print $4 }')
  sinks=$(
    pactl list sink-inputs | \
    awk 'BEGIN { sink = "" } {
        if ($0 ~ "^Sink Input #") {
          sink = substr($3, 2)
        }
        if (sink != "" && tolower($0) ~ tolower("application.(name|icon_name|process.binary) = \"'"$class"'\"$")) {
          print sink
          sink = ""
        }
    }'
  )
  echo "$sinks"
}

# display help if no arguments supplied
if [ $# -ne 1 ]; then
  panic "$(help)"
fi

# command line argument
arg="$1"

# display help if no expected arguments supplied
case $arg in
  up|upapp|down|downapp|restore|restoreapp|toggle|toggleapp)
    ;;
  *)
    # unknown argument
    panic "$(help)"
    ;;
esac

# options
case $arg in
  up)
    pactl set-sink-volume "@DEFAULT_SINK@" +${voladjust}%
    ;;
  upapp)
    for sink in $(getappsinks); do
      pactl set-sink-input-volume "$sink" +${voladjust}%
    done
    ;;
  down)
    pactl set-sink-volume "@DEFAULT_SINK@" -${voladjust}%
    ;;
  downapp)
    for sink in $(getappsinks); do
      pactl set-sink-input-volume "$sink" -${voladjust}%
    done
    ;;
  restore)
    pactl set-sink-volume "@DEFAULT_SINK@" ${volmaster}%
    ;;
  restoreapp)
    for sink in $(getappsinks); do
      pactl set-sink-input-volume "$sink" ${volmaster}%
    done
    ;;
  toggle)
    pactl set-sink-mute "@DEFAULT_SINK@" toggle
    ;;
  toggleapp)
    for sink in $(getappsinks); do
      pactl set-sink-input-mute "$sink" toggle
    done
    ;;
esac
