#!/bin/sh

# strict mode
set -eu

# settings
progname="volume"
# value for master volume
volmaster="90"
# value for increase/decrease volume
voladjust="5"

# help usage info
help() {
  echo "Usage: $progname up|down|toggle|restore"
}

# shows the message and exits the program
panic() {
  echo "$@" 1>&2
  exit 1
}

# display help if no arguments supplied
if [ $# -ne 1 ]; then
  panic "$(help)"
fi

# command line argument
arg="$1"

# display help if no expected arguments supplied
case $arg in
  up|down|restore|toggle)
    ;;
  *)
    # unknown argument
    panic "$(help)"
    ;;
esac

# default sink
sink=$(pacmd list-sinks | awk '/\* index: / { print $NF }')
if ! [ "$sink" -eq "$sink" ] 2>/dev/null; then
  panic "Error: default sink is non-numeric"
fi

# options
case $arg in
  up)
    pactl set-sink-volume "$sink" +${voladjust}%
    ;;
  down)
    pactl set-sink-volume "$sink" -${voladjust}%
    ;;
  restore)
    pactl set-sink-volume "$sink" ${volmaster}%
    ;;
  toggle)
    pactl set-sink-mute "$sink" toggle
    ;;
esac
