#!/bin/sh

# strict mode
set -eu

progname="weather"
city="$*"

# display help if no arguments supplied
if [ $# -eq 0 ]; then
  echo "Usage: $progname city"
  exit 1
fi

# get city weather
curl -s http://wttr.in/"${city}"?0mT | awk '{ if (NR == 4) print $(NF-1),$NF }'
