#!/bin/sh
# Distributed under the terms of the GNU General Public License v3

# strict mode
set -eu

progname="weather"
city=$(echo "$*" | sed 's/[[:space:]]/%20/g')

# display help if no arguments supplied
if [ $# -eq 0 ]; then
  echo "Usage: $progname city"
  exit 1
fi

# get city weather
curl -s http://wttr.in/"${city}"?0mT | awk '{ if (NR == 4) print $(NF-1),$NF }'
