#!/bin/sh
# Distributed under the terms of the GNU General Public License v3

# strict mode
set -eu

# used with sleep on ~/.xinitrc to print dwm system date correctly
echo $((60 - $(/bin/date +%S | sed 's/^0\([0-9]\)/\1/')))
