#!/bin/sh

# ensure that these programs exist
programs="xprop awk"
for program in $programs; do
  if ! command -v "$program" >/dev/null 2>&1; then
    echo "Error: program $program is missing!"
    exit 1
  fi
done

# get window manager name property
xprop -root -f WM_NAME "8u" | \
awk -F '=' '/WM_NAME\(STRING\) = / { 
  gsub(/^ "|"$/, "", $2)
  print $2 
}'
