#!/bin/sh
# Distributed under the terms of the GNU General Public License v3

# strict mode
set -eu

# get window manager name property
xprop -root -f WM_NAME "8u" | \
awk -F '=' '/WM_NAME\(STRING\) = / { 
  gsub(/^ "|"$/, "", $2)
  print $2 
}'
