#!/bin/sh
# Distributed under the terms of the GNU General Public License v3

# strict mode
set -eu

# only url as arg1
if [ $# -ne 1 ]; then
  echo "Usage:"
  echo "  yda url"
  exit 1
fi
url="$1"

# audio output file
case $url in
  *[\?\&]list=*)
    playlist="--yes-playlist"
    output="%(playlist)s/%(playlist_index)s-%(title)s.%(ext)s"
    ;;
  *)
    playlist="--no-playlist"
    output="%(title)s.%(ext)s"
    ;;
esac

# download the audio file
exec youtube-dl \
  --ignore-errors \
  --prefer-ffmpeg \
  --audio-quality 0 \
  --format bestaudio \
  --extract-audio \
  --audio-format mp3 \
  "$playlist" \
  --output "$output" "$url"
